export const data = [
    {
        "id": "0",
        "img":"./material/img/aptParis01.jpg",
        "type": "apartment",
        "location": "paris",
        "direction": "25 Rue des Pyramides, 75001",
        "area": "800 Sq Ft.",
        "bedroom" : "3",
        "toilets" : "2",
        "price" : "1050",
        "status":  "rent",
        "parking" : "none",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "6 month ago",
        "descripcion" : "El apartamento se encuentra en un edificio que esta ubicado en el centro de la ciudad, buenas vistas y buen comercio."
    },

    {
        "id": "1",
        "img":"./material/img/aptParis02.jpg",
        "type": "apartment",
        "location": "paris",
        "direction" : "22 Avenue Marceau, 75008",
        "area": "1300 Sq Ft.",
        "bedroom" : "2",
        "toilets" : "2",
        "price" : "1450",
        "status":  "rent",
        "parking" : "none",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "9 month ago",
        "descripcion" : "El apartamento se encuentra en un edificio que esta ubicado en el centro de la ciudad, buenas vistas y buen comercio."
    },

    {
        "id": "2",
        "img":"./material/img/aptParis03.jpg",
        "type": "apartment",
        "location": "paris",
        "direction": "4 rue de la Montagne Sainte-Geneviève - 75005",
        "area": "800 Sq Ft.",
        "bedroom" : "3",
        "toilets" : "2",
        "price" : "1050",
        "status":  "rent",
        "parking" : "none",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "6 month ago",
        "descripcion" : "El apartamento se encuentra en un edificio que esta ubicado en el centro de la ciudad, buenas vistas y buen comercio."
    },

    {
        "id": "3",
        "img":"./material/img/houseLondon01.jpg",
        "type": "house",
        "location": "London",
        "direction" : "50-56 Willesden Ln, London NW6 7SX",
        "area": "4050 Sq ft.",
        "bedroom" : "9",
        "toilets" : "5",
        "price" : "450,000,000",
        "status":  "Sale",
        "parking" : "10",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "01 day ago",
        "descripcion" : "La casa es muy cara, es muy buena y acogedora, un lujo solo de ricos."
    },

    {
        "id": "4",
        "img":"./material/img/aptLondon02.jpg",
        "type": "apartment",
        "location": "London",
        "direction" : "44 Regent St, Soho, London W1B 5RA",
        "area": "2800 Sq ft.",
        "bedroom" : "5",
        "toilets" : "3",
        "price" : "650,000",
        "status":  "Sale",
        "parking" : "2",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "20 day ago",
        "descripcion" : "El apartamento tiene una increible vista, un lugar inspirador para los amantes de la fotografia."
    },

    {
        "id": "5",
        "img":"./material/img/aptLondon03.jpg",
        "type": "apartment",
        "location": "London",
        "direction": "256 Grays Inn Rd, London WC1X 8LD",
        "area": "1500 Sq ft.",
        "bedroom" : "2",
        "toilets" : "1",
        "price" : "90,000",
        "status":  "Sale",
        "parking" : "10",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "2 months ago",
        "descripcion" : "Un apartamento completamente increible, equipado con todo lo necesario, a tras un edificio que solo Elon Musk podria comprar, pero el apartamento esta bueno."
    },

    {
        "id": "6",
        "img":"./material/img/houseMadrid01.jpg",
        "type": "House",
        "location": "Madrid",
        "direction" : "Calle de Alcalá, 28014 Madrid",
        "area": "7800 Sq ft.",
        "bedroom" : "500",
        "toilets" : "300",
        "price" : "150,000,000",
        "status":  "Sale",
        "parking" : "10",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "01 day ago",
        "descripcion" : "Una casa para apoyar al Santiago Bernabeu y recordar los momentos de Cristiano Ronaldo."
    },

    {
        "id": "7",
        "img":"./material/img/casaMadrid02.jpg",
        "type": "House",
        "location": "Madrid",
        "direction" : "Plaza Mayor, 28012 Madrid",
        "area": "3080 Sq ft.",
        "bedroom" : "9",
        "toilets" : "5",
        "price" : "50,000,000",
        "status":  "Sale",
        "parking" : "1",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "05 day ago",
        "descripcion" : "Una casa inspirada en tu tia que vive en Barcelona."
    },

    {
        "id": "8",
        "img":"./material/img/casaMadrid03.jpg",
        "type": "House",
        "location": "Madrid",
        "direction" : "Calle de Gran Vía, 28013 Madrid",
        "area": "3070 Sq ft.",
        "bedroom" : "5",
        "toilets" : "3",
        "price" : "20,000,000",
        "status":  "Sale",
        "parking" : "3",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "09 months ago",
        "descripcion" : "Una casa para vivir en las afueras de Valencia, pero que te hace sentir en el centro de Madrid."
    },

    {
        "id": "9",
        "img":"./material/img/villaViena01.jpg",
        "type": "Town",
        "location": "Viena",
        "direction" : "Stadtpark, 1030 Viena",
        "area": "11000 Sq ft.",
        "bedroom" : "9700",
        "toilets" : "2000",
        "price" : "950,000,000",
        "status":  "Sale",
        "parking" : "5000",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "today ago",
        "descripcion" : "Si deseas recrear la epoca de los festines de las bellas en las grandes Cortes, esta es tu oportunidad."
    },

    {
        "id": "10",
        "img":"./material/img/villaViena02.jpg",
        "type": "Town",
        "location": "Viena",
        "direction" : "Calle de Ringstrasse, 1010 Viena",
        "area": "10500 Sq ft.",
        "bedroom" : "6700",
        "toilets" : "3500",
        "price" : "450,000,000",
        "status":  "Sale",
        "parking" : "1000",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "01 day ago",
        "descripcion" : "Por que tantas habitaciones? No lo se, Por que tantos banos?, tampoco lo se, lo que si se es que tu quieres esta Villa."
    },

    {
        "id": "11",
        "img":"./material/img/aptViena03.jpg",
        "type": "apartment",
        "location": "Viena",
        "direction" : "Calle de Mariahilferstrasse, 1060 Viena",
        "area": "2050 Sq ft.",
        "bedroom" : "4",
        "toilets" : "2",
        "price" : "2000",
        "status":  "rent",
        "parking" : "1",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "02 years ago",
        "descripcion" : "La casa es muy cara, es muy buena y acogedora, un lujo solo de ricos."
    },

    {
        "id": "12",
        "img":"./material/img/villaToscana01.jpg",
        "type": "Town",
        "location": "La Toscana",
        "direction" : "Piazza del Duomo, 50122 Florencia",
        "area": "9999 Sq ft.",
        "bedroom" : "79",
        "toilets" : "49",
        "price" : "1500000",
        "status":  "rent",
        "parking" : "150",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "02 months ago",
        "descripcion" : "Una villa para disfrutar de la historia de la Italia renacentista."
    },

    {
        "id": "13",
        "img":"./material/img/houseToscana02.jpg",
        "type": "House",
        "location": "La Toscana",
        "direction" : "Calle de Viale dei Cipressi, 53019 Castellina in Chianti",
        "area": "1350 Sq ft.",
        "bedroom" : "3",
        "toilets" : "1",
        "price" : "750",
        "status":  "rent",
        "parking" : "none",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "03 months ago",
        "descripcion" : "Una casa para disfrutar la pobreza de La Toscana."
    },

    {
        "id": "14",
        "img":"./material/img/houseToscana03.jpg",
        "type": "House",
        "location": "La Toscana",
        "direction" : "Calle de Piazza della Signoria, 50122 Florencia",
        "area": "2600 Sq ft.",
        "bedroom" : "1",
        "toilets" : "none",
        "price" : "250",
        "status":  "rent",
        "parking" : "none",
        "owner" : "Brian Steven",
        "phone" : "123 45678",
        "date" : "05 days ago",
        "descripcion" : "El arte y las bellas de florencia, la ciencia que florecio un dia inspirada en tu propia casa."
    },
]
